frame_id: map
default_direction: forward
default_densify_ds: 0.0
paths:
  1:
    direction: backward
    points:
    - - 0.325
      - 2.985
    - - 0.325
      - 1.985
    - - 0.325
      - 0.985
    - - 0.325
      - 0.0
    - - 0.325
      - -0.2
    - - 0.65
      - -0.325
    - - 1.65
      - -0.325
    - - 2.65
      - -0.325
    - - 3.65
      - -0.325
    - - 4.06
      - -0.325
    - - 4.35
      - -0.2
    - - 4.35
      - 0.0
    - - 4.35
      - 0.885
  2:
    direction: backward
    points:
    - - 4.35
      - 0.885
    - - 4.35
      - 1.5
    - - 4.35
      - 2.0
    - - 4.35
      - 2.5
    - - 4.35
      - 3.0
    - - 4.35
      - 3.5
    - - 4.35
      - 4.0
    - - 4.35
      - 4.5
    - - 4.35
      - 5.0
    - - 4.35
      - 5.5
    - - 4.35
      - 6.0
    - - 4.35
      - 6.5
    - - 4.35
      - 7.0
    - - 4.35
      - 7.63
  3:
    direction: forward
    points:
    - - 4.35
      - 7.63
    - - 4.35
      - 7.0
    - - 4.35
      - 6.5
    - - 4.35
      - 6.0
    - - 4.35
      - 5.5
    - - 4.35
      - 5.0
    - - 4.35
      - 4.5
    - - 4.35
      - 4.0
    - - 4.35
      - 3.5
    - - 4.35
      - 3.0
    - - 4.35
      - 2.5
    - - 4.35
      - 2.0
    - - 4.35
      - 1.5
    - - 4.35
      - 0.885
  4:
    direction: forward
    points:
    - - 4.35
      - 0.885
    - - 4.35
      - 0.0
    - - 4.35
      - -0.2
    - - 4.06
      - -0.325
    - - 3.65
      - -0.325
    - - 2.65
      - -0.325
    - - 1.65
      - -0.325
    - - 0.65
      - -0.325
    - - 0.325
      - -0.2
    - - 0.325
      - 0.0
    - - 0.325
      - 0.985
    - - 0.325
      - 1.985
    - - 0.325
      - 2.985
  5:
    direction: forward
    points:
    - - 0.0
      - 0.0
    - - 0.0
      - 0.5
  6:
    direction: backward
    points:
    - - 0.0
      - 0.5
    - - 0.0
      - 0.0
  108:
    direction: forward
    generated_from:
      station_start: OmniFire
      station_end: LC
    points:
    - - 4.35
      - 0.885
    - - 4.355
      - 0.885
    - - 4.355
      - 0.325
    - - 4.345
      - -0.325
    - - 3.345
      - -0.325
    - - 2.345
      - -0.325
    - - 1.345
      - -0.325
    - - 0.65
      - -0.325
    - - 0.325
      - 0.325
    - - 0.325
      - 1.325
    - - 0.325
      - 2.325
    - - 0.325
      - 2.985
  118:
    direction: backward
    generated_from:
      station_start: LC
      station_end: OmniFire
    points:
    - - 0.325
      - 2.985
    - - 0.325
      - 1.985
    - - 0.325
      - 0.985
    - - 0.325
      - 0.325
    - - 0.65
      - -0.325
    - - 1.65
      - -0.325
    - - 2.65
      - -0.325
    - - 3.65
      - -0.325
    - - 4.345
      - -0.325
    - - 4.355
      - 0.325
    - - 4.355
      - 0.885
    - - 4.35
      - 0.885
